### ISSUE TITLE
MoCo-v3 results code

### ISSUE THREAD

**Issue by LokeshBadisa** [jiaminchen-1031/transformerinterp#4]
How can I get explanation map for MoCo-v3? Using `ssl=True` isn't giving the results from paper.

**Comment by Monson2002** [comment]
HI @LokeshBadisa can you help me with how to reproduce the code given here, I am not able to find the model .pth files which are required

`
⚡ ~/ViT PYTHONPATH=$(pwd) CUDA_VISIBLE_DEVICES=0 python baselines/ViT/imagenet_sseg_eval.py --method ours --imagenet-seg-path dataset/gtsegs_ijcv.mat
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/ViT/baselines/ViT/imagenet_seg_eval.py", line 141, in <module>
    model = vit_base_patch16_224_dino(pretrained=True).cuda()
  File "/teamspace/studios/this_studio/ViT/baselines/ViT/ViT_new.py", line 360, in vit_base_patch16_224_dino
    load_pretrained(
  File "/teamspace/studios/this_studio/ViT/baselines/ViT/helpers.py", line 97, in load_pretrained
    state_backbone = torch.load(cfg['url_backbone'], map_location='cpu')
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '/root/datasets/models/pretrained_model/dino_vitbase16_pretrain.pth'
`

**Comment by LokeshBadisa** [comment]
path for weights is not set properly. change the weights path.
